# Generated by Django 5.0.7 on 2024-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.TextField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255)),
                ('cduration', models.IntegerField()),
            ],
        ),
    ]
