# Generated by Django 5.0.7 on 2024-08-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemgt', '0001_initial'),
        ('studentmgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='coursemgt.course'),
        ),
    ]
