# Generated by Django 5.0.7 on 2024-09-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgt', '0002_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pr_phone',
            field=models.CharField(default='9999999999', max_length=20),
            preserve_default=False,
        ),
    ]
