# Generated by Django 5.0.7 on 2024-09-24 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgt', '0003_student_pr_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
