# Generated by Django 5.0.7 on 2024-09-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgt', '0005_remove_student_batch_student_batch_mon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch_year',
            field=models.IntegerField(max_length=255),
        ),
    ]
