# Generated by Django 5.0.7 on 2024-09-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgt', '0006_alter_student_batch_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch_year',
            field=models.IntegerField(),
        ),
    ]
