# Generated by Django 5.0.7 on 2024-09-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
